version: '2.1'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  auth-service:
    build: auth-service
    ports:
      - 5000:5000

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017

  vikings-service:
    build: vikings-service
    ports:
      - 6000:6000

  vikings-mongodb:
    build: mongodb
    ports:
      - 26000:27017

  sail-service:
    build: sail-service
    ports:
      - 7000:7000

  sail-mongodb:
    build: mongodb
    ports:
      - 27000:27017

  equipment-service:
    build: equipment-service
    ports:
      - 8000:8000

  equipment-mongodb:
    build: mongodb
    ports:
      - 28000:27017

  monitoring:
    build: monitoring